{{- if not .Values.hashiCorpVault.enabled }}
{{- if or (not .Values.license) (not .Values.adminPassword) }}
{{- fail "License and adminPassword need to be set if HashiCorp Vault is not used." }}
{{- end }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "foundry-vtt.fullname" . }}
  labels:
    {{- include "foundry-vtt.labels" . | nindent 4 }}
type: Opaque
stringData:
  adminKey: {{ .Values.adminPassword | default "changeme" | quote }}
  license: {{ .Values.license | default "changeme" | quote }}
  license.json: |-
    {
      "license": "{{ .Values.license | default "changeme" }}"
    }
{{- end -}}