---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "foundry-vtt.fullname" . }}
  labels:
    {{- include "foundry-vtt.labels" . | nindent 4 }}
type: Opaque
stringData:
  adminKey: {{ .Values.adminPassword | default "changeme" | quote }}
  license: |-
    {
      "license": "{{ .Values.license | default "changeme" }}"
    }