apiVersion: v2
name: foundry-vtt
description: |-
  A chart for deploying Foundry Virtual Tabletop (VTT) on k8s.
  
  CHANGELOG
  =========
  2.1.3 Patience could reduce patch levels
        * handling the external secret correctly.
  2.1.2 Doing it right would be easier
        * handle the license key better.
  2.1.1 Lazy peoples curse
        * external secrets operators apiVersion is v1 not v1beta1. Copy'n'paste can be a curse ...
  2.1.0 Secret Management with External Secrets
        * Added support for External Secret Operator with HashiCorp Vault integration.
  2.0.0 Initial release
        * First version to deploy Foundry VTT 13.x on k8s using the fleddy/foundryvtt image.
maintainers:
  - name: klenkes74
    email: rlichti@kaiserpfalz-edv.de
    url: https://www.lichti.de
type: application
version: 2.1.3
